apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: s2i-test-commit1
    application: s2i-test-commit1
    template: ed-nodejs-8-basic-s2i
    xpaas: 1.2.0
  name: s2i-test-commit1
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.22.240.36:5000/01-oscp-demo-t/s2i-test-commit1:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
